# Generated by Django 4.1 on 2023-01-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_authoer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='authoer',
            new_name='author',
        ),
    ]
